/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    ApplicationForm: typeof import('./src/components/JobDetail/ApplicationForm.vue')['default']
    AttachmentsList: typeof import('./src/components/JobDetail/AttachmentsList.vue')['default']
    AttachmentsSection: typeof import('./src/components/JobDetail/AttachmentsSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    GdprAgreement: typeof import('./src/components/JobDetail/GdprAgreement.vue')['default']
    JobDescription: typeof import('./src/components/JobDetail/JobDescription.vue')['default']
    JobDetail: typeof import('./src/components/JobDetail.vue')['default']
    JobHeader: typeof import('./src/components/JobDetail/JobHeader.vue')['default']
    JobList: typeof import('./src/components/JobList.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    PersonalInfoSection: typeof import('./src/components/JobDetail/PersonalInfoSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalarySection: typeof import('./src/components/JobDetail/SalarySection.vue')['default']
    SocialMediaSection: typeof import('./src/components/JobDetail/SocialMediaSection.vue')['default']
    SubmitButton: typeof import('./src/components/JobDetail/SubmitButton.vue')['default']
  }
}
